spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    mapper-locations: "classpath:mapper/**/*.xml"
    jdbc-url: jdbc:mysql://localhost:3306/schedule?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false
  sql:
    init:
      mode: always
